---
- name: Copy percona xtrabackup
  ansible.builtin.copy:
    src: percona-xtrabackup-80-8.0.31-24.1.el7.x86_64.rpm
    dest: /home/percona-xtrabackup-80-8.0.31-24.1.el7.x86_64.rpm
    owner: root
    group: root
    mode: '0644'

- name: Install xtrabackup rpms
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - socat
    - pigz
    - /home/percona-xtrabackup-2.3.6-1.el7.x86_64.rpm