---
- name: Generate ssh key
  ansible.builtin.shell: |
    if test -f "mhaKey" && test -f "mhaKey.pub"; then
      echo "mhaKey already exists"
    else
      ssh-keygen -b 2048 -t rsa -f ./mhaKey -q -N ''
    fi
  connection: local
  ignore_errors: true
  run_once: true

- name: Read publickey
  ansible.builtin.command: "cat ./mhaKey.pub"
  connection: local
  register: mha_public_key
  run_once: true

- name: Create mha directory
  ansible.builtin.file:
    path: "{{ mha_base_path }}"
    state: directory
    owner: "{{ mha_ssh_user }}"
    group: "{{ mha_ssh_user }}"
    mode: 0755

- name: Copy publickey to authorized_keys file
  ansible.builtin.lineinfile:
    dest: ~/.ssh/authorized_keys
    line: "{{ mha_public_key.stdout }}"

- name: Copy privatekey to remote server
  ansible.builtin.copy:
    src: ./mhaKey
    dest: "{{ mha_base_path }}/mhaKey"
    owner: root
    group: root
    mode: 0600

- name: Copy publickey to remote server
  copy:
    src: ./mhaKey.pub
    dest: "{{ mha_base_path }}/mhaKey.pub"
    owner: root
    group: root
    mode: 0600