---
- name: Copy my.cnf mysql configuration
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644

- name: Create directories if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
  loop:
    - "{{ mysql_base_dir }}/data"
    - "{{ mysql_base_dir }}/log"
    - "{{ mysql_base_dir }}/run"

- name: Ensure mysqld is started and enabled on boot
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true
  register: mysql_service_configuration

- debug:
    var: mysql_service_configuration

- name: Extract mysql temporary password
  ansible.builtin.shell: |
    echo $(grep 'temporary password' /mysql/log/mysqld.log | awk '{print $13}')
  register: mysql_temp_password
  check_mode: no

- name: Update mysql root password
  ansible.builtin.shell: |
    mysql -u root -p'{{ mysql_temp_password.stdout }}' --connect-expired-password -NBe "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
  ignore_errors: true
