---
  - name: get last server id
    shell: |
      cat /home/user/server_id.ini
    register: last_mysql_server_id
    check_mode: no
    delegate_to: localhost
    tags:
      - server-id

  - name: get new server id
    shell: |
      echo "$(({{ last_mysql_server_id.stdout }}+1))"
    register: new_mysql_server_id
    check_mode: no
    delegate_to: localhost
    tags:
      - server-id

  - name: save new server id
    shell: |
      echo -n "{{ new_mysql_server_id.stdout }}" > /home/user/server_id.ini
    check_mode: no
    delegate_to: localhost
    tags:
      - server-id

  - debug:
      var: new_mysql_server_id.stdout
    tags:
      - server-id

  - name: Replace conf file with template
    template:
      src: server_id.cnf.j2
      dest: /etc/my.cnf.d/server_id.cnf
    vars:
      server_id: "{{ new_mysql_server_id.stdout }}"