---
- ansible.builtin.include_tasks: variables.yml

- ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: configure.yml
- ansible.builtin.include_tasks: replication-server-id.yml
  when: inventory_hostname == item
  with_items: "{{ ansible_play_hosts }}"
  tags:
    - server-id
- ansible.builtin.include_tasks: replication.yml
- ansible.builtin.include_tasks: replication-semisync.yml
  tags:
    - mysql-semisync