---
- name: Download mysql 8.0.31 rpm bundle
  ansible.builtin.shell: |
    if test -f "/home/mysql-8.0.31.tar"; then
      echo "mysql-8.0.31.tar already exists"
    else
      wget https://downloads.mysql.com/archives/get/p/23/file/mysql-8.0.31-1.el9.x86_64.rpm-bundle.tar -O /home/mysql-8.0.31.tar
    fi

- name: Unarchive mysql.tar
  ansible.builtin.unarchive:
    src: /home/mysql-8.0.31.tar
    dest: /home/
    remote_src: true

- name: Install mysql rpms
  ansible.builtin.shell: |
    if ! (yum list installed | grep "mysql-community-server"); then
      yum install -y mysql-community-*.rpm
    else
      exit 0
    fi

- name: Install mysql rpms
  ansible.builtin.yum:
    name: "MySQL-python"
    state: present
