---
- name: Inject mha config
  ansible.builtin.template:
    src: mha.cnf.j2
    dest: "{{ mha_conf_path }}"

- name: Copy mhamanager.service mhamanager service
  ansible.builtin.template:
    src: mhamanager.service.j2
    dest: /etc/systemd/system/mhamanager.service

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure mhamanager is started and enabled on boot
  ansible.builtin.service:
    name: mhamanager
    state: started
    enabled: true
  become: yes
  become_user: root
  register: mhamanager_service_configuration

- debug:
    var: mhamanager_service_configuration